engines:
  tesseract:
    psm: 6
    lang: "eng"
    tesseract_cmd: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"  # Windows
  
  easyocr:
    languages: ["en"]
    gpu: true
    
  trocr:
    model_name: "microsoft/trocr-base-handwritten"
    device: "cuda"
    max_new_tokens: 128

preprocessing:
  enhancement_level: "high"  # For better handwritten text
  preserve_aspect_ratio: true

postprocessing:
  min_confidence: 0.3  # Lower for handwritten text
  min_word_length: 1

parallel_processing: true
max_workers: 3
log_level: "INFO"