# Settings actually used by the library

quality_analyzer:
  sharpness_threshold: 0.1
  noise_threshold: 0.3
  contrast_threshold: 0.4
  brightness_range: [0.2, 0.8]
  enhancement_threshold: 0.6
  edge_detection_kernel_size: 3
  blur_kernel_size: 15

image_enhancer:
  noise_reduction:
    enabled: true
    method: "gaussian"
    kernel_size: 5
  contrast_enhancement:
    enabled: true
    method: "clahe"
    clip_limit: 2.0
    tile_grid_size: [8, 8]
  sharpening:
    enabled: true
    method: "unsharp_mask"
    radius: 1.0
    amount: 1.5
  denoising:
    enabled: true
    h: 10
    template_window_size: 7
    search_window_size: 21

engine_manager:
  parallel_processing: true
  max_workers: 4
  timeout_per_engine: 30