# Text Detection Configuration
detection:
  method: "craft"
  confidence_threshold: 0.7
  
  craft:
    text_threshold: 0.7
    link_threshold: 0.4
    low_text: 0.4
    cuda: true
    canvas_size: 1280
    mag_ratio: 1.5
    
  east:
    confidence_threshold: 0.5
    nms_threshold: 0.4
    input_width: 320
    input_height: 320

# Post-processing
postprocessing:
  min_confidence: 0.5
  nms_threshold: 0.3
  min_area: 100
  aspect_ratio_range: [0.1, 10.0]

# Region filtering
filtering:
  min_width: 10
  min_height: 5
  max_width: 2000
  max_height: 1000
  overlap_threshold: 0.3